name: Build

on:
  push:
    branches: [ $default-branch ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-versions: '16.4.0' 
      
      - name: Checkout Books
        uses: actions/checkout@v2
        with:
          path: app
      
      - name: Checkout FrappeJS
        uses: actions/checkout@v2
        with:
          repository: 'frappe/frappejs'
          path: framework

        
      - name: Setup FrappeJS
        run: |
          cd framework/frappejs
          yarn
          yarn link

      - name: Setup Books
        run: |
          cd app/books
          yarn
          yarn link frappejs

      - name: Run build
        run: yarn electron:build --linux