name: Build

on:
  push:
    branches: [$default-branch]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  setup_and_build:
    runs-on: macos-11
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Set yarn version
        run: yarn set version 1.22.17

      - name: Checkout Books
        uses: actions/checkout@v2

      - name: Setup Books
        run: yarn

      - name: Install RPM
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm

      - name: Run build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          APPLE_NOTARIZE: 0
        run: yarn electron:build -mwl --publish never
